name: BenTest
favicon: null
layout_spectrum: 0.39332
typography_spectrum: 0.4611640144139528
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6723114857450128
  lightness: 0.7363633301574737
  saturation: 0.7312837315257639
  rhythmicContrast: 0.1352955149486661
purpose: []
