name: BenTest
favicon: null
layout_spectrum: 0.39332
typography_spectrum: 0.25516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#567dca'
    - '#a1bedc'
    - '#130f10'
    - '#ff802c'
    - '#ac3537'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
